### ISSUE TITLE
bug in the script at line 155

### ISSUE THREAD

**Issue by jstefka** [Mohak91/MetReTrim#1]
Is it possible that the python script contains a typo at line 155?
there it reads:
	regex_list=regex.findall("(%s){s<=%d}"%(primer,mismatch_list),seq)
but probably should be:
	regex_list=regex.findall("(%s){s<=%d}"%(primer,mismatch_int),seq)

Otherwise, the trimming doesn't run for me.
Best, Jan.

**Comment by Mohak91** [comment]
Hey Jan,

Thanks for bringing the issue to my notice. The script should work fine now. 
Hope this was helpful.

Happy trimming!

Best, 
Mohak
